import { Hero } from '@/components';
import style from './about.module.scss';

export const metadata = {
  title: 'Aidel - Nosotros',
  description: 'Generated by create next app',
};

const About = () => {
  return (
    <main className={style.about}>
      <Hero text={true} bground='/assets/image/about.jpg' title='nosotros' />
      <div className={style.about__container}>
        <p className={style.about__paragraph}>
          Tiene como misión principal impulsar el crecimiento económico
          sostenible y el desarrollo local en la región. A través de la
          aplicación de la inteligencia y el análisis de datos, AIDEL busca
          promover la toma de decisiones informadas y estratégicas para
          fortalecer los sectores productivos, fomentar la inversión y mejorar
          la calidad de vida de la comunidad satipeña.
        </p>
        <p className={style.about__paragraph}>
          AIDEL se dedica a recopilar, procesar y mostrar información relevante
          sobre los recursos económicos de Satipo. Utilizando métodos de
          investigación y herramientas tecnológicas avanzadas, el equipo de
          AIDEL identifica oportunidades de crecimiento, detecta desafíos y
          propone soluciones innovadoras que impulsen el desarrollo económico
          local de manera inclusiva y sostenible.
        </p>
        <p className={style.about__paragraph}>
          La misión de AIDEL se basa en la creencia de que el conocimiento y la
          inteligencia aplicados de manera estratégica pueden generar un impacto
          significativo en la economía local. A través de la generación de
          información precisa y la formulación de políticas y estrategias
          basadas en evidencia, AIDEL busca fomentar la competitividad de los
          sectores productivos, fortalecer la capacidad empresarial y promover
          la creación de empleo.
        </p>
      </div>
    </main>
  );
};

export default About;
