import '@/styles/global.css';

import { Navbar } from '@/components';
import { Routes } from '@/models';
import { madurai, pridi, roboto } from './models';

export const metadata = {
  title: 'Aidel - Inicio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='es-PE'>
      <body
        className={`${pridi.variable} ${roboto.variable} ${madurai.variable}`}
      >
        <Navbar
          pathNames={[
            Routes.ABOUT,
            Routes.INSTITUTION,
            Routes.INTERVENTION,
            // Routes.GEOPORTAL,
            // Routes.REPOSITORIO,
          ]}
        />
        {children}
      </body>
    </html>
  );
}
